### ISSUE TITLE
Build breaker for .Net Core sonar cloud analysis with Azure DevOps

### ISSUE THREAD

**Issue by SanthoshYalamuri** [simondel/sonar-buildbreaker-vsts#20]
Hello,

We are using sonarcloud to analyze .net core projects with Azure DevOps.

Tasks in the pipeline:

```
task: CmdLine@2
displayName: Dotnet sonarscanner start
inputs:
script: |
echo Dotnet sonarscanner start
dotnet “SonarScanner.MSBuild.dll” begin /k:"" /o:"" /d:sonar.host.url=“https://sonarcloud.io” /d:sonar.login=""

Task to execute .net core build

task: CmdLine@2
displayName: Dotnet sonarscanner end
inputs:
script: |
echo Dotnet sonarscanner end
dotnet “$(Build.SourcesDirectory)\Tools\Sonarqube\SonarScanner.MSBuild.dll” end

- task: sonarcloud-buildbreaker@2
  inputs:
    SonarCloud: 'sonarcloud'
    organization: 'genomics'
```

We are getting the below logs from the build breaker task:

```
Starting: sonarcloudbuildbreaker

==============================================================================


Task         : SonarCloud build breaker

Description  : Break the build when the quality gate fails.

Version      : 2.1.0

Author       : Simon de Lang

Help         : 

==============================================================================

Number of analyses in this build: 0

Summary of statusses: 

Finishing: sonarcloudbuildbreaker` 

```

Not sure why the output contains "Number of analyses in this build: 0".

Also the build should be failed, but it succeeds. Not sure what's wrong in the pipeline setup.

Any inputs will be helpful. Thanks in advance.
