### ISSUE TITLE
[Ehancement]Get the analysis result in variable

### ISSUE THREAD

**Issue by jumorelle** [simondel/sonar-buildbreaker-vsts#29]
I would like to execute a task after the build breaker if the quality gate failed. Something like this would help:

```yaml
- task: sonar-buildbreaker@8
  name: buildbreaker
  displayName: Check Quality Gate
  continueOnError: true
  inputs:
    SonarQube: SonarQube
    OutputVariableName: myVariableName
- task: xxxxx
  condition: $(buildbreaker.myVariableName)
  ...
```

I can submit a PR if you want.
