### ISSUE TITLE
Build Breaker don't see SonarCloud scans

### ISSUE THREAD

**Issue by yyf-test** [simondel/sonar-buildbreaker-vsts#31]
We have CI/CD, built on AzureDevops. Quality Gate Job with SonarCloud scan. 
Everything was OK and it was working. Here is example of output:

```
==============================================================================
Task         : SonarCloud build breaker
Description  : Break the build when the quality gate fails.
Version      : 2.1.2
Author       : Simon de Lang
Help         : 
==============================================================================
Number of analyses in this build: 1
Summary of statusses: "ERROR"
##[error]The analysis did not pass the quality gate because because at least one analysis has has the status 'ERROR'. Attempting to fail the build!
Finishing: Break build on quality gate failure
```

Then 12.06.2023 I turned off build breaker (needed for testing)

 And the problem is that when I turned it on back yesterday (14.06.2023), SonarCloud Build Breaker stopped to break builds when Sonar scan find something. So I checked the output of the build breaker step and found that it cannot see the scan result. Output of task is following:

```
==============================================================================
Task         : SonarCloud build breaker
Description  : Break the build when the quality gate fails.
Version      : 2.1.2
Author       : Simon de Lang
Help         : 
==============================================================================
Number of analyses in this build: 0
Summary of statusses: 
Finishing: Break build on quality gate failure
```

What that could be?
The only difference I see is that version of SonarCloud task is different. In scans few days ago, SonarCloud Publish  task version was 1.11.3. Now - it is 1.13.0

Here is also part of YAML used in our pipeline:
```
- task: SonarCloudAnalyze@1
  displayName: 'SonarCloud: Code Analysis'

- task: SonarCloudPublish@1
  displayName: 'SonarCloud: Publish Result'

- task: SimondeLang.sonarcloud-buildbreaker.sonar-buildbreaker.sonarcloud-buildbreaker@2
  displayName: 'SonarCloud: Break build on quality gate failure'
  condition: eq(variables['Build.Reason'], 'PullRequest')
  inputs:
    SonarCloud: 'SonarCloud'
    organization: 'XXXXXXXXXXXXX'
```

**Comment by yyf-test** [comment]
After some investigation found following: 
 - **Build Breaker** task trying to find report-task.txt using following path pattern: **`$(Agent.TempDirectory)/sonar/$(Build.BuildNumber)/**/report-task.txt`**
 - **SonarCloud** tasks by default saving report-task.txt file in **`$(Agent.TempDirectory)/sonar/$(Build.Id)/<XXXXXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXX>/report-task.txt`**. 
 
After adding following **extraProperties** for for **SonarCloud Prepare** task `sonar.scanner.metadataFilePath=$(Agent.TempDirectory)/sonar/$(Build.BuildNumber)/test/report-task.txt` , **Build Breaker** found **report-task.txt** and again started to work as expected.

My assumption is that newest version of SonarCloud tasks changed default folder for report-task.txt file which Build Breaker task was referenced to. By adding extra property in SonarCloud Prepare task with explicit path to report-task.txt file, Build Breaker able to find the file and work as expected:
```
- task: SonarCloudPrepare@1
  displayName: 'SonarCloud: Prepare for Analysis'
  inputs:
    SonarCloud: XXXXXXX
    organization: 'XXXXXXXXXXXXXXX'
    projectKey: '$(Build.Repository.Name)'
    projectName: $(Build.Repository.Name)
    extraProperties: |
      sonar.scanner.metadataFilePath=$(Agent.TempDirectory)/sonar/$(Build.BuildNumber)/test/report-task.txt
```
